name: first workflow
env:
 WORKFLOW_VAR: "This variable is declared at workflow level"
on:
  workflow_dispatch:

jobs:
   firstjob:
     runs-on: ubuntu-latest
     steps:
       - name: firstJob script
         shell: bash
         run: echo Hello world! first job
       - uses: actions/checkout@v4
         name: This is a checkout action
         id: CheckoutAction
       - name: Print to Log
         id: print-to-log
         uses: actions/hello-world-javascript-action@main
         with:
           who-to-greet: ${{ github.actor }}
       - name: time
         run: |
           echo "The time of the greeting was at: ${{ steps.print-to-log.outputs.time }}"
   secondjob:
     env:
       JOB_VAR: "This is a job variable"
     needs: firstjob
     runs-on: ubuntu-latest
     steps:
       - name: secondJob script
         shell: bash
         run: |
           echo this is second job
           echo this is a multiline script
       - name: environment variables
         env:
           STEP_VAR: "This is a step level variable"
         run: |
          echo "$WORKFLOW_VAR"
          echo "$JOB_VAR"
          echo "$STEP_VAR"
          echo "The following is a secret ${{ secrets.SOME_SECRET }}
          echo "The following are default environment variables"
          echo "$GITHUB.ACTOR"
          echo "$GITHUB_JOB"
          echo "$GITHUB_REF"
